"""add is_published and scheduled_for to posts

Revision ID: 115e15dd3e07
Revises: 8fa8abda22c2
Create Date: 2026-09-16 01:40:32.541313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115e15dd3e07'
down_revision: Union[str, Sequence[str], None] = '8fa8abda22c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'scheduled_for')
    op.drop_column('posts', 'is_published')
    # ### end Alembic commands ###
