"""add flier_image_url to event_details

Revision ID: 865cd5f80c29
Revises: 115e15dd3e07
Create Date: 2026-09-16 23:44:02.053767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865cd5f80c29'
down_revision: Union[str, Sequence[str], None] = '115e15dd3e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_details', sa.Column('flier_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_details', 'flier_image_url')
    # ### end Alembic commands ###
